# Generated by Django 4.2 on 2026-07-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_group', models.CharField(help_text='e.g. Under 14, Under 17', max_length=50)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='academy.academy')),
            ],
        ),
    ]
