# Generated by Django 4.2 on 2026-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='M-Pesa Screenshot Upload', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receipt_no', models.CharField(max_length=100, unique=True)),
                ('verified_by_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
