# Generated by Django 4.2 on 2026-08-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0003_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('VISA', 'Visa card'), ('MASTERCARD', 'MasterCard'), ('KCB', 'KCB bank transfer'), ('COOP_BANK', 'Co-operative Bank transfer')], default='MPESA', max_length=20),
        ),
    ]
