# Generated by Django 4.2 on 2026-07-14 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('academy', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('potential_overall', models.IntegerField(help_text='Rating out of 99', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('PROVEN', 'Proven')], default='PROSPECT', max_length=15)),
                ('comments', models.TextField()),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_reports', to='academy.academy')),
                ('linked_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_links', to='players.player')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.scoutprofile')),
            ],
        ),
    ]
