# Generated by Django 4.2 on 2026-07-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schedule', '0001_initial'),
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Teams.team'),
        ),
    ]
