# Generated by Django 4.2 on 2026-07-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('age_group', models.CharField(default='Under 14', max_length=50)),
                ('player_code', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('medical_info', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(help_text='Emergency contact details', max_length=255)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='academy.academy')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='Teams.team')),
            ],
        ),
    ]
