# Generated by Django 4.2 on 2026-07-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schedule', '0001_initial'),
        ('players', '0001_initial'),
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='players.player'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='Schedule.schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('player', 'schedule')},
        ),
    ]
